#cloud-config

runcmd:
  # Set Administrator password
  - net user Administrator "PackerPassword@123"

  # Enable PowerShell Remoting
  - powershell -Command "Enable-PSRemoting -Force"

  # WinRM basic HTTP configuration
  - powershell -Command "winrm quickconfig -force"
  - powershell -Command "winrm set winrm/config/service @{AllowUnencrypted='true'}"
  - powershell -Command "winrm set winrm/config/service/auth @{Basic='true'}"

  # Improve WinRM stability
  - powershell -Command \"winrm set winrm/config @{MaxTimeoutms='1800000'}\"
  - powershell -Command \"winrm set winrm/config/winrs @{MaxMemoryPerShellMB='2048'}\"
  - powershell -Command \"Set-Item -Path WSMan:\\localhost\\Service\\Auth\\Basic -Value \$true\"
  - powershell -Command \"net localgroup 'Remote Management Users' Administrator /add\"

  # Ensure HTTP listener
  - powershell -Command \"winrm delete winrm/config/Listener?Address=*+Transport=HTTP\" 
  - powershell -Command \"winrm create winrm/config/Listener?Address=*+Transport=HTTP\"

  # Firewall rule
  - netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in action=allow localport=5985

  # Start WinRM service
  - powershell -Command "Set-Service WinRM -StartupType Automatic"
  - powershell -Command "Start-Service WinRM"

  # Ensure WinRM is fully initialized
  - powershell -Command "Start-Sleep -Seconds 20"

  - echo "WinRM enabled and configured via cloud-config runcmd"